signing_key_path = "/signing_key"
issuer = "http://keycloak:8080/realms/waldur"
# optionally test with dev-kc
# issuer = "https://keycloak-dev.isambard.ac.uk/realms/isambard"
client_id = "clifton"
log_format = "json"

extensions = ["permit-pty", "permit-agent-forwarding", "permit-port-forwarding"]

internal_strip_portal_from_project = true

[platforms."brics.aip1.clusters.shared"]
alias = "aip1.isambard"
hostname = "ai-p1.access.isambard.ac.uk"
proxy_jump = "ai.login.isambard.ac.uk"

[platforms."brics.aip2.clusters.shared"]
alias = "aip2.isambard"
hostname = "ai-p2.access.isambard.ac.uk"
proxy_jump = "ai.login.isambard.ac.uk"

[platforms."brics.i3.clusters.shared"]
alias = "3.isambard"
hostname = "i3.access.isambard.ac.uk"
proxy_jump = "ai.login.isambard.ac.uk"

[platforms."brics.i3.clusters.macs"]
alias = "macs3.isambard"
hostname = "i3macs.access.isambard.ac.uk"
proxy_jump = "ai.login.isambard.ac.uk"

[platforms."brics.dl.clusters.bc5"]
alias = "bc5.digital-labs"
hostname = "digital-labs.bristol.ac.uk"

[[mappers]]
project_infra = "v1"
